name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker images
      run: |
        docker build -t jacksoncuevas/hacksondev-react-app
        docker push jacksoncuevas/hacksondev-react-app
    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        password: ${{ secrets.DO_PASSWORD }}
        script: |
          docker rmi -f $(docker image ls -a -q)
          docker pull jacksoncuevas/hacksondev-react-app
          docker stop hacksondev-react-container || true
          docker rm hacksondev-react-container || true
          docker run -d --name hacksondev-react-container -p 81:3001 jacksoncuevas/hacksondev